#!/usr/bin/env python3
"""Render CATALOG.csv from .tools/catalog.json and regenerate the README.md
in every data/ folder that has catalog entries.

Run this after every fetch run so CATALOG.csv and per-folder READMEs stay in
sync with the files actually present.
"""
import csv
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CATALOG_JSON = os.path.join(ROOT, ".tools", "catalog.json")
CATALOG_CSV = os.path.join(ROOT, "CATALOG.csv")
DATA = os.path.join(ROOT, "data")

COLUMNS = ["folder", "filename", "description", "source", "source_url",
           "published", "lines_last_redrawn", "features"]


def main():
    with open(CATALOG_JSON, encoding="utf-8") as f:
        cat = json.load(f)
    rows = []
    for key in sorted(cat):
        e = dict(cat[key])
        folder = e["folder"]
        # warn (but keep) entries whose file is missing
        path = os.path.join(ROOT, "data", folder, e["filename"])
        missing = not os.path.exists(path)
        rows.append([e.get("folder", ""), e.get("filename", "")] +
                    [str(e.get(c, "")) for c in COLUMNS[2:]])
        if missing:
            print(f"WARNING: catalog entry {key} but file missing", file=sys.stderr)

    with open(CATALOG_CSV, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(COLUMNS + ["missing_on_disk"])
        for r in rows:
            w.writerow(r + ["yes" if not os.path.exists(os.path.join(ROOT, "data", r[0], r[1])) else ""])
    print(f"wrote {CATALOG_CSV} with {len(rows)} entries")

    # per-folder READMEs
    folders = {}
    for key, e in cat.items():
        folders.setdefault(e["folder"], []).append(e)
    for folder, entries in sorted(folders.items()):
        fdir = os.path.join(ROOT, "data", folder)
        os.makedirs(fdir, exist_ok=True)
        lines = [f"# {folder}\n",
                 "Files in this folder (auto-generated by tools/make_catalog.py):\n"]
        for e in sorted(entries, key=lambda x: x["filename"]):
            lines.append(f"## {e['filename']}")
            for c in ["description", "source", "source_url", "published",
                      "lines_last_redrawn", "features"]:
                if e.get(c):
                    lines.append(f"- **{c}**: {e[c]}")
            lines.append("")
        with open(os.path.join(fdir, "README.md"), "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
    print(f"updated README.md in {len(folders)} folders")


if __name__ == "__main__":
    main()
